name: Deploy to Vercel
on:
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          cd client
          npm install

      - name: Build project
        run: |
          cd client
          npm run build

      - name: Install Vercel CLI
        run: |
          cd client
          npm install -g vercel

      - name: Deploy to Vercel
        run: |
          cd client
          vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --confirm
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

